# Signing tasks configuration (TOML)

# Define one or more signing tasks using the [[tasks]] array.
# For each task, set:
# - task_name: Identifier for this task (used for profile lookup)
# - app_name: Human-friendly app name (used for profile naming: "{app_name} Dev")
# - bundle_id: iOS Bundle Identifier (must exist in Apple Developer Portal)
# - ipa_url: Direct download URL of the original IPA to sign
# - asset_server_path: Destination path on the asset server; if it ends with '/', the signed file name will be appended

[[tasks]]
task_name = "JHenTai"
app_name = "JHenTai"
bundle_id = "io.zeroclover.app.jhentai"
repo_url = "https://github.com/jiangtian616/JHenTai"
asset_server_path = "/itms.zeroclover.io/JHenTai/JHenTai.ipa"

[[tasks]]
task_name = "Eros FE"
app_name = "Eros FE"
bundle_id = "io.zeroclover.io.apps.eros-fe"
repo_url = "https://github.com/3003h/Eros-FE"
asset_server_path = "/itms.zeroclover.io/fehviewer/Eros-FE.ipa"

[[tasks]]
task_name = "Asspp"
app_name = "Asspp"
bundle_id = "io.zeroclover.app.asspp"
repo_url = "https://github.com/Lakr233/Asspp"
asset_server_path = "/itms.zeroclover.io/Asspp/Asspp.ipa"

[[tasks]]
task_name = "PiliPlus"
app_name = "PiliPlus"
bundle_id = "io.zeroclover.app.piliplus"
repo_url = "https://github.com/bggRGjQaUbCoE/PiliPlus"
asset_server_path = "/itms.zeroclover.io/PiliPlus/PiliPlus.ipa"
